Repository raulwwq0/pinia-spanish-docs, pull requests merged in 2023-01, with the labels that each got.

#3 docs(core-concepts): state.md translated
  core-concepts/state.md
Labels: new-translation

#5 fix: use english anchors
  cookbook/hot-module-replacement.md
  cookbook/index.md
  cookbook/migration-vuex.md
  cookbook/options-api.md
  cookbook/testing.md
  core-concepts/index.md
  core-concepts/state.md
  getting-started.md
  introduction.md
Labels: enhancement

#6 docs(core-concepts): getters.md and actions.md translated
  core-concepts/actions.md
  core-concepts/getters.md
Labels: new-translation

#8 fix(cookbook): migrating vuex anchor
  .vitepress/locales/es.js
  cookbook/migration-vuex.md
Labels: bug

#11 docs(cookbook): Add translation to migration-0-0-7.md
  cookbook/migration-0-0-7.md
Labels: new-translation

#12 feat: add api files to translate
  .vitepress/locales/es.js
  api/enums/pinia.MutationType.md
  api/index.md
  api/interfaces/pinia.DefineSetupStoreOptions.md
  api/interfaces/pinia.DefineStoreOptions.md
  api/interfaces/pinia.DefineStoreOptionsBase.md
  api/interfaces/pinia.DefineStoreOptionsInPlugin.md
  api/interfaces/pinia.MapStoresCustomization.md
  api/interfaces/pinia.Pinia.md
  api/interfaces/pinia.PiniaCustomProperties.md
  api/interfaces/pinia.PiniaCustomStateProperties.md
  api/interfaces/pinia.PiniaPlugin.md
  api/interfaces/pinia.PiniaPluginContext.md
  api/interfaces/pinia.StoreDefinition.md
  api/interfaces/pinia.StoreProperties.md
  api/interfaces/pinia.SubscriptionCallbackMutationDirect.md
  api/interfaces/pinia.SubscriptionCallbackMutationPatchFunction.md
  api/interfaces/pinia.SubscriptionCallbackMutationPatchObject.md
  api/interfaces/pinia._StoreOnActionListenerContext.md
  api/interfaces/pinia._StoreWithState.md
  api/interfaces/pinia._SubscriptionCallbackMutationBase.md
  api/interfaces/pinia_testing.TestingOptions.md
  api/interfaces/pinia_testing.TestingPinia.md
  api/modules/pinia.md
  api/modules/pinia_nuxt.md
  api/modules/pinia_testing.md
  cookbook/testing.md
Labels: documentation

#13 docs: plugins.md and outside-component-usage.md translated
  core-concepts/outside-component-usage.md
  core-concepts/plugins.md
Labels: new-translation

#14 docs(ssr): index.md and nuxt.md translated
  .vitepress/locales/es.js
  cookbook/composables.md
  core-concepts/index.md
  introduction.md
  ssr/index.md
  ssr/nuxt.md
Labels: new-translation, better-translation

#20 docs: Translate the `[api/interfaces]` section
  api/interfaces/pinia_testing.TestingOptions.md
  api/interfaces/pinia_testing.TestingPinia.md
Labels: new-translation

#18 docs(api): modules section translated
  api/modules/pinia.md
  api/modules/pinia_nuxt.md
  api/modules/pinia_testing.md
Labels: new-translation
